<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
<<<<<<< HEAD
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Mpdf\\' => array($vendorDir . '/mpdf/mpdf/src'),
    'DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
=======
    'PHPMailer\\PHPMailer\\' => array($vendorDir . '/phpmailer/phpmailer/src'),
>>>>>>> parent of a8ee426... Instalando e configurando o PHPMailer
);
