<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Categorias' => $baseDir . '/model/Categorias.class.php',
    'Clientes' => $baseDir . '/model/Clientes.class.php',
    'Conexao' => $baseDir . '/model/Conexao.class.php',
    'Config' => $baseDir . '/model/Config.class.php',
    'Dados' => $baseDir . '/model/Dados.class.php',
    'Dashboard' => $baseDir . '/model/Dashboard.class.php',
    'EasyPeasyICS' => $vendorDir . '/phpmailer/phpmailer/extras/EasyPeasyICS.php',
    'EnviarEmail' => $baseDir . '/model/EnviarEmail.class.php',
    'Login' => $baseDir . '/model/Login.class.php',
    'Ordensservicos' => $baseDir . '/model/Ordensservicos.class.php',
    'PHPMailer' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
    'PHPMailerOAuth' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauth.php',
    'PHPMailerOAuthGoogle' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauthgoogle.php',
    'POP3' => $vendorDir . '/phpmailer/phpmailer/class.pop3.php',
    'Paginacao' => $baseDir . '/model/Paginacao.class.php',
    'Prioridades' => $baseDir . '/model/Prioridades.class.php',
    'Rotas' => $baseDir . '/model/Rotas.class.php',
    'SMTP' => $vendorDir . '/phpmailer/phpmailer/class.smtp.php',
    'Servicos' => $baseDir . '/model/Servicos.class.php',
    'Sistema' => $baseDir . '/model/Sistema.class.php',
    'Tecnicos' => $baseDir . '/model/Tecnicos.class.php',
    'Template' => $baseDir . '/model/Template.class.php',
    'ntlm_sasl_client_class' => $vendorDir . '/phpmailer/phpmailer/extras/ntlm_sasl_client.php',
    'phpmailerException' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
);
