<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdef0b5187e22a9c63dca4d271d80364e
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'ClienteModal' => __DIR__ . '/../..' . '/model/ClienteModal.class.php',
        'Clientes' => __DIR__ . '/../..' . '/model/Clientes.class.php',
        'Conexao' => __DIR__ . '/../..' . '/model/Conexao.class.php',
        'Config' => __DIR__ . '/../..' . '/model/Config.class.php',
        'Dados' => __DIR__ . '/../..' . '/model/Dados.class.php',
        'Ordensservicos' => __DIR__ . '/../..' . '/model/Ordensservicos.class.php',
        'Paginacao' => __DIR__ . '/../..' . '/model/Paginacao.class.php',
        'Prioridades' => __DIR__ . '/../..' . '/model/Prioridades.class.php',
        'Rotas' => __DIR__ . '/../..' . '/model/Rotas.class.php',
        'Sistema' => __DIR__ . '/../..' . '/model/Sistema.class.php',
        'Tecnicos' => __DIR__ . '/../..' . '/model/Tecnicos.class.php',
        'Template' => __DIR__ . '/../..' . '/model/Template.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdef0b5187e22a9c63dca4d271d80364e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdef0b5187e22a9c63dca4d271d80364e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitdef0b5187e22a9c63dca4d271d80364e::$classMap;

        }, null, ClassLoader::class);
    }
}
